#==========================================================================================================================
# PROJECT NAME & DESC
#==========================================================================================================================
name: seedeal03
description: A new Flutter project.
#==========================================================================================================================
# PUBLISH TO
#==========================================================================================================================
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#==========================================================================================================================
# VERSION
#==========================================================================================================================
version: 1.0.0+1
#==========================================================================================================================
# ENVIRONMENT
#==========================================================================================================================
environment:
  sdk: ">=2.7.0 <3.0.0"

#==========================================================================================================================
# DEPENDENCY
#==========================================================================================================================
dependencies:
  flutter:
    sdk: flutter

#==========================================================================================================================
# ADD PACKAGE
#==========================================================================================================================
  cupertino_icons: ^0.1.3
  flutter_auth_buttons: ^0.8.0
  flutter_statusbarcolor: ^0.2.3  
  country_pickers: ^1.3.0
  intl: ^0.16.1
  scoped_model: ^1.0.1  
  flutter_launcher_icons: ^0.7.5
  #===========================================================
  # LOGGER
  #===========================================================    
  logger: ^0.8.3    
  #===========================================================
  # GOOGLE SIGN-IN (FIREBASE)
  #===========================================================  
  firebase_core: ^0.4.4+3       # FIREBASE CORE
  firebase_auth: ^0.16.0        # LOGIN BY FIREBASE ACCOUNT
  google_sign_in: ^4.0.1+1      # LOGIN BY GOOGLE ACCOUNT
  apple_sign_in: ^0.1.0         # LOGIN BY APPLE
  device_info: ^0.4.1+4         # LOGIN BY APPLE
  # flutter_facebook_login: ^2.0.0   # LOGIN BY FACEBOOK (DONT USE --> IMAGE PICKER)
  #===========================================================
  # FIREBASE: CLOUD, DB, STORAGE
  #===========================================================  
  cloud_firestore: ^0.13.3  
  firebase_database: ^3.1.3 
  firebase_storage: ^3.1.6   
  #===========================================================
  # IMAGE PICKER
  #===========================================================    
  image_picker: ^0.6.7+3
  #===========================================================
  # GEN KEY
  #===========================================================   
  uuid: ^2.0.4  

#==========================================================================================================================
# PATH FOR ICON GEN
#==========================================================================================================================
flutter_icons:
  image_path: "assets/icons/seedellogo.png"
  android: true
  ios: true

#==========================================================================================================================
# DEV DEPENDENCY
#==========================================================================================================================
dev_dependencies:
  flutter_test:
    sdk: flutter

#==========================================================================================================================
# FLUTTER CONFIG
#==========================================================================================================================
flutter:
  uses-material-design: true

#==========================================================================================================================
# ASSET
#==========================================================================================================================  
  assets:
    - assets/images/    

